### ISSUE TITLE
alias does not exist

### ISSUE THREAD

**Issue by midaut** [Hakky54/mutual-tls-ssl#77] opened 2020-10-18 10:49 UTC
**Describe the bug**
Error message :
keytool error: java.lang.Exception: Alias \<server\> does not exist

**To Reproduce**
Run following command
keytool -keystore client/src/test/resources/truststore.jks -delete -alias server -storepass secret

**Expected behavior**
alias deleted correctly

**Environmental Data:**
Debian GNU/Linux 10 (buster)

**Comment by Hakky54** [comment] 2020-10-19 22:33
Hi @midaut 

Thank you for sharing your issue over here. I have retried it on a clean Debian environment and I didn't had this error message. It could successfully clean the truststore. Did you maybe save your server certificate under a different alias within the truststore of the client?

Could you execute the following command and share the output of it?
```keytool -list -v -keystore client/src/test/resources/truststore.jks | grep Alias```

**Comment by Hakky54** [comment] 2020-12-14 23:25
Closing this issue because I didn't get any response for the last two months. Please reopen this issue if it is still occurring.

**Closed by Hakky54** 2020-12-14 23:25 UTC

**Comment by WilliamM7** [comment] 2023-09-18 19:41
The problem is the sequence you are trying to type your command with. The `keytool` command must follow a command then the options. Try:

`keytool -delete -keystore <keystore> -alias server`
